'use client'

import { useMemo, useState } from 'react'
import { ArrowRight, Check, ChevronDown, Heart, Camera, Mail, MapPin, Menu, MessageCircle, Minus, Plus, Search, ShoppingBag, Star, X } from 'lucide-react'
import { suppliedProducts } from './lumora-supplied-products'

type Product = { id: number; brand: string; name: string; category: string; price: number; description: string; image: string; badge?: string }

type CartItem = Product & { quantity: number }

// Indicative Nairobi retail prices in KSh; final prices can vary by size, retailer and promotion.
const products: Product[] = [
  { id: 1, brand: 'Acnes', name: 'Acnes Sealing Jell', category: 'Skincare', price: 950, description: 'Targeted gel for blemish-prone skin.', image: '/products/clay-mask.png' },
  { id: 2, brand: 'Acnes', name: 'Acnes Creamy Wash', category: 'Skincare', price: 1100, description: 'Gentle daily cleanser for oily skin.', image: '/products/glow-mist.png' },
  { id: 3, brand: 'Bio Balance', name: 'Skin Bliss Moisturiser', category: 'Skincare', price: 1850, description: 'Comforting hydration for everyday skin.', image: '/products/body-butter.png' },
  { id: 4, brand: 'Bio-Oil', name: 'Skincare Oil 125ml', category: 'Skincare', price: 2200, description: 'Iconic oil for scars, stretch marks and dry skin.', image: '/products/baobab-oil.png', badge: 'Bestseller' },
  { id: 5, brand: 'Bodycology', name: 'Sweet Love Body Mist', category: 'Body Care', price: 1650, description: 'Lightly scented mist for a soft finish.', image: '/products/glow-mist.png' },
  { id: 6, brand: 'CeraVe', name: 'Foaming Cleanser 236ml', category: 'Skincare', price: 2900, description: 'Ceramides and niacinamide for normal-oily skin.', image: '/products/hero-beauty.png' },
  { id: 7, brand: 'CeraVe', name: 'Moisturising Cream 340g', category: 'Body Care', price: 3600, description: 'Rich barrier-supporting cream with ceramides.', image: '/products/body-butter.png' },
  { id: 8, brand: "Dr Teal's", name: 'Epsom Salt Soaking Solution', category: 'Wellness', price: 2100, description: 'A restorative mineral bath ritual.', image: '/products/candle.png' },
  { id: 9, brand: 'Fillerina', name: 'Grade 2 Day and Night Cream', category: 'Skincare', price: 7800, description: 'Plumping care for a smoother-looking complexion.', image: '/products/baobab-oil.png' },
  { id: 10, brand: 'Garnier', name: 'Vitamin C Sheet Mask', category: 'Skincare', price: 450, description: 'Brightening single-use facial mask.', image: '/products/clay-mask.png' },
  { id: 11, brand: 'Garnier', name: 'Micellar Cleansing Water', category: 'Skincare', price: 1450, description: 'Makeup-removing water for a fresh cleanse.', image: '/products/glow-mist.png' },
  { id: 12, brand: 'Keyara Botanics', name: 'African Black Soap', category: 'Body Care', price: 950, description: 'Botanical cleansing bar made for a fresh feel.', image: '/products/body-butter.png' },
  { id: 13, brand: 'La Roche-Posay', name: 'Anthelios SPF50+', category: 'Skincare', price: 3900, description: 'High protection daily face sunscreen.', image: '/products/hero-beauty.png', badge: 'Popular' },
  { id: 14, brand: 'L’Oréal Paris', name: 'Revitalift Filler Serum', category: 'Skincare', price: 4200, description: 'Hyaluronic acid serum for a bouncy glow.', image: '/products/baobab-oil.png' },
  { id: 15, brand: 'Magic Drops', name: 'Gluta Glow Serum', category: 'Skincare', price: 1850, description: 'Lightweight glow serum for an even-looking tone.', image: '/products/glow-mist.png' },
  { id: 16, brand: 'Makari', name: 'Carotonic Brightening Cream', category: 'Skincare', price: 2650, description: 'Nourishing care for a radiant-looking complexion.', image: '/products/clay-mask.png' },
  { id: 17, brand: 'Melano CC', name: 'Vitamin C Essence', category: 'Skincare', price: 3200, description: 'Japanese vitamin C care for daily brightening.', image: '/products/baobab-oil.png' },
  { id: 18, brand: 'Nice & Lovely', name: 'Cocoa Butter Lotion', category: 'Body Care', price: 650, description: 'Classic moisturising body lotion.', image: '/products/body-butter.png' },
  { id: 19, brand: 'Oxygen Botanicals', name: 'Oxygen Cleanser', category: 'Skincare', price: 2800, description: 'Professional botanical cleanser for a clear feel.', image: '/products/glow-mist.png' },
  { id: 20, brand: 'Simple', name: 'Kind to Skin Face Wash', category: 'Skincare', price: 1350, description: 'No-fuss cleanser for sensitive skin.', image: '/products/hero-beauty.png' },
  { id: 21, brand: 'Skin by Zaron', name: 'Hydra Glow Serum', category: 'Skincare', price: 1800, description: 'Light serum made for a luminous finish.', image: '/products/baobab-oil.png' },
  { id: 22, brand: 'Skin by Zaron', name: 'Tinted Lip Oil', category: 'Makeup', price: 950, description: 'Glossy comfort with a sheer wash of colour.', image: '/products/lip-balm.png' },
  { id: 23, brand: 'Uncover', name: 'The Sunset', category: 'Skincare', price: 2850, description: 'Daily SPF50 sunscreen with a soft finish.', image: '/products/hero-beauty.png', badge: 'Kenyan favourite' },
  { id: 24, brand: 'Uncover', name: 'Bright Side Serum', category: 'Skincare', price: 2600, description: 'Brightening serum with a gentle daily feel.', image: '/products/glow-mist.png' },
  ...suppliedProducts,
]

const categories = ['All products', 'Skincare', 'Body Care', 'Hair Care', 'Makeup', 'Wellness']
const brands = ['All brands', ...Array.from(new Set(products.map((product) => product.brand)))]
const formatPrice = (price: number) => `KSh ${price.toLocaleString('en-KE')}`

function Logo() {
  return <a href="#top" className="flex items-center gap-3" aria-label="Lumora Beauty Shop home"><img src="/lumora-logo.png" alt="Lumora Beauty Shop" className="h-12 w-auto object-contain" /></a>
}

function ProductCard({ product, addToCart }: { product: Product; addToCart: (product: Product) => void }) {
  return <article className="group flex flex-col">
    <div className="relative aspect-[4/5] overflow-hidden rounded-[1.5rem] bg-[#eee7df]">
      {product.badge && <span className="absolute left-4 top-4 z-10 rounded-full bg-[#b96752] px-3 py-1 text-[10px] font-semibold uppercase tracking-[0.18em] text-white">{product.badge}</span>}
      <button aria-label={`Save ${product.name}`} className="absolute right-4 top-4 z-10 rounded-full bg-white/80 p-2 text-[#593f36] opacity-0 transition group-hover:opacity-100"><Heart className="size-4" /></button>
      <img src={product.image} alt={product.name} className="size-full object-cover transition duration-500 group-hover:scale-105" />
      <button onClick={() => addToCart(product)} className="absolute bottom-4 left-4 right-4 translate-y-3 rounded-full bg-[#3d2b27] py-3 text-sm font-medium text-white opacity-0 transition group-hover:translate-y-0 group-hover:opacity-100">Add to basket</button>
    </div>
    <div className="flex items-start justify-between gap-3 pt-4">
      <div><p className="text-[10px] font-semibold uppercase tracking-[0.16em] text-[#b96752]">{product.brand}</p><h3 className="mt-1 font-serif text-lg text-[#3d2b27]">{product.name}</h3><p className="mt-1 text-xs leading-5 text-[#806f68]">{product.description}</p></div>
      <span className="shrink-0 text-sm font-semibold text-[#593f36]">{formatPrice(product.price)}</span>
    </div>
  </article>
}

export function LumoraStore() {
  const [category, setCategory] = useState('All products')
  const [brand, setBrand] = useState('All brands')
  const [query, setQuery] = useState('')
  const [cart, setCart] = useState<CartItem[]>([])
  const [cartOpen, setCartOpen] = useState(false)
  const [checkoutOpen, setCheckoutOpen] = useState(false)
  const [feedbackSent, setFeedbackSent] = useState(false)
  const filtered = products.filter((p) => (category === 'All products' || p.category === category) && (brand === 'All brands' || p.brand === brand) && `${p.brand} ${p.name} ${p.description}`.toLowerCase().includes(query.toLowerCase()))
  const total = useMemo(() => cart.reduce((sum, item) => sum + item.price * item.quantity, 0), [cart])
  const itemCount = cart.reduce((sum, item) => sum + item.quantity, 0)
  const addToCart = (product: Product) => setCart((items) => items.some((i) => i.id === product.id) ? items.map((i) => i.id === product.id ? { ...i, quantity: i.quantity + 1 } : i) : [...items, { ...product, quantity: 1 }])
  const adjust = (id: number, amount: number) => setCart((items) => items.map((i) => i.id === id ? { ...i, quantity: i.quantity + amount } : i).filter((i) => i.quantity > 0))

  return <div id="top" className="min-h-screen bg-[#f8f5f0] text-[#3d2b27]">
    <div className="bg-[#3d2b27] px-4 py-2 text-center text-[10px] font-medium uppercase tracking-[0.2em] text-[#f8f5f0]">Complimentary Nairobi delivery on orders over KSh 4,000</div>
    <header className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 lg:px-10"><Logo /><nav className="hidden items-center gap-8 text-sm text-[#705c54] md:flex"><a href="#shop" className="hover:text-[#b96752]">Shop</a><a href="#story" className="hover:text-[#b96752]">Our story</a><a href="#reviews" className="hover:text-[#b96752]">Reviews</a><a href="#contact" className="hover:text-[#b96752]">Contact</a></nav><div className="flex items-center gap-2"><button aria-label="Search products" className="rounded-full p-2 text-[#593f36] hover:bg-[#eee7df]"><Search className="size-5" /></button><button onClick={() => setCartOpen(true)} className="relative rounded-full p-2 text-[#593f36] hover:bg-[#eee7df]" aria-label={`Open basket with ${itemCount} items`}><ShoppingBag className="size-5" />{itemCount > 0 && <span className="absolute -right-1 -top-1 flex size-4 items-center justify-center rounded-full bg-[#b96752] text-[9px] text-white">{itemCount}</span>}</button><button className="rounded-full p-2 md:hidden" aria-label="Open menu"><Menu className="size-5" /></button></div></header>
    <main>
      <section className="mx-auto grid max-w-7xl gap-10 px-5 pb-20 pt-8 lg:grid-cols-[0.9fr_1.1fr] lg:items-center lg:px-10 lg:pt-16"><div className="max-w-xl"><p className="mb-6 flex items-center gap-3 text-[11px] font-semibold uppercase tracking-[0.25em] text-[#b96752]"><span className="h-px w-8 bg-[#b96752]" /> Beauty, rooted in place</p><h1 className="font-serif text-5xl leading-[1.02] text-[#3d2b27] sm:text-7xl">Your daily ritual,<br /><em className="font-normal text-[#b96752]">made luminous.</em></h1><p className="mt-7 max-w-md text-base leading-7 text-[#806f68]">Thoughtfully made beauty essentials inspired by the warmth, colour and botanicals of Kenya. Simple rituals, beautiful results.</p><div className="mt-9 flex flex-wrap gap-3"><a href="#shop" className="inline-flex items-center gap-3 rounded-full bg-[#b96752] px-6 py-3 text-sm font-semibold text-white transition hover:bg-[#96503f]">Explore the collection <ArrowRight className="size-4" /></a><a href="#story" className="rounded-full border border-[#d9c9c0] px-6 py-3 text-sm font-medium text-[#593f36] hover:bg-white">Our story</a></div></div><div className="relative mx-auto w-full max-w-xl"><div className="overflow-hidden rounded-[2rem] bg-[#d7b7a6]"><img src="/products/hero-beauty.png" alt="Lumora skincare products surrounded by botanical leaves" className="aspect-[5/4] w-full object-cover" /></div><div className="absolute -bottom-5 -left-4 rounded-2xl bg-[#f8f5f0] px-5 py-4 shadow-lg sm:-left-8"><p className="font-serif text-2xl text-[#b96752]">01</p><p className="text-[10px] uppercase tracking-[0.16em] text-[#806f68]">Made with intention</p></div></div></section>
      <section id="shop" className="mx-auto max-w-7xl scroll-mt-8 px-5 py-16 lg:px-10"><div className="mb-8 flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[0.25em] text-[#b96752]">The edit</p><h2 className="mt-2 font-serif text-4xl text-[#3d2b27]">Find your glow</h2></div><div className="flex flex-wrap gap-2">{categories.map((c) => <button key={c} onClick={() => setCategory(c)} className={`rounded-full px-4 py-2 text-xs transition ${category === c ? 'bg-[#3d2b27] text-white' : 'border border-[#d9c9c0] text-[#806f68] hover:bg-white'}`}>{c}</button>)}</div></div><div className="mb-5 flex items-center gap-3 overflow-x-auto pb-1" aria-label="Shop by brand">{brands.map((b) => <button key={b} onClick={() => setBrand(b)} className={`shrink-0 rounded-full px-4 py-2 text-xs transition ${brand === b ? 'bg-[#b96752] text-white' : 'border border-[#d9c9c0] text-[#806f68] hover:bg-white'}`}>{b}</button>)}</div><p className="mb-8 text-xs text-[#9a857b]">Prices shown are indicative Nairobi retail prices in Kenya and may vary by size, retailer and promotion.</p><div className="mb-8 flex items-center justify-between border-b border-[#e3d8d0] pb-4"><span className="text-sm text-[#806f68]">{filtered.length} products {brand !== 'All brands' ? `from ${brand}` : ''}</span><label className="flex items-center gap-2 text-sm text-[#806f68]"><span className="sr-only">Search products</span><Search className="size-4" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search the edit" className="w-32 bg-transparent outline-none placeholder:text-[#a99a91] sm:w-48" /></label></div><div className="grid gap-x-5 gap-y-12 sm:grid-cols-2 lg:grid-cols-3">{filtered.map((product) => <ProductCard key={product.id} product={product} addToCart={addToCart} />)}</div></section>
      <section id="story" className="bg-[#e9ddd3] px-5 py-20 lg:px-10"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-2 lg:items-center"><div className="overflow-hidden rounded-[2rem]"><img src="/products/story-botanicals.png" alt="Botanical ingredients used by Lumora" className="aspect-[4/3] w-full object-cover" /></div><div className="max-w-lg"><p className="text-[10px] font-semibold uppercase tracking-[0.25em] text-[#b96752]">The Lumora way</p><h2 className="mt-3 font-serif text-4xl leading-tight">Beauty that feels like coming home.</h2><p className="mt-5 text-base leading-7 text-[#705c54]">We believe the best rituals are the ones you look forward to. Lumora brings together nourishing African botanicals, considered formulas and the little luxuries that make an ordinary morning feel special.</p><div className="mt-7 grid grid-cols-2 gap-5 border-t border-[#cdbbb0] pt-6 text-sm"><div><strong className="font-serif text-xl">Kenyan</strong><p className="mt-1 text-[#806f68]">Inspired ingredients</p></div><div><strong className="font-serif text-xl">Small batch</strong><p className="mt-1 text-[#806f68]">Made with care</p></div></div></div></div></section>
      <section id="reviews" className="mx-auto max-w-7xl px-5 py-20 lg:px-10"><div className="grid gap-8 lg:grid-cols-[0.7fr_1.3fr]"><div><p className="text-[10px] font-semibold uppercase tracking-[0.25em] text-[#b96752]">Kind words</p><h2 className="mt-3 font-serif text-4xl">Loved by your skin.</h2><p className="mt-4 text-sm leading-6 text-[#806f68]">Tell us about your Lumora ritual. Your notes help our little shop grow.</p></div><div className="grid gap-4 sm:grid-cols-2"><blockquote className="rounded-2xl bg-[#f0e6de] p-6"><div className="flex gap-1 text-[#b96752]">{[1,2,3,4,5].map((i) => <Star key={i} className="size-3 fill-current" />)}</div><p className="mt-4 font-serif text-xl leading-7">“The glow oil is now the one thing I never skip. My skin feels so soft.”</p><cite className="mt-5 block text-xs not-italic text-[#806f68]">— Wanjiku, Kilimani</cite></blockquote><form onSubmit={(e) => { e.preventDefault(); setFeedbackSent(true) }} className="flex flex-col gap-3 rounded-2xl border border-[#e3d8d0] p-6"><label className="text-sm font-semibold">Share your experience</label><input required placeholder="Your name" className="rounded-xl border border-[#d9c9c0] bg-transparent px-4 py-3 text-sm outline-none focus:border-[#b96752]" /><textarea required placeholder="What did you love?" rows={3} className="resize-none rounded-xl border border-[#d9c9c0] bg-transparent px-4 py-3 text-sm outline-none focus:border-[#b96752]" />{feedbackSent ? <p className="flex items-center gap-2 text-sm text-[#52705e]"><Check className="size-4" /> Thank you for sharing.</p> : <button className="rounded-full bg-[#3d2b27] py-3 text-sm font-semibold text-white">Send feedback</button>}</form></div></div></section>
    </main>
    <footer id="contact" className="bg-[#3d2b27] px-5 py-12 text-[#f8f5f0] lg:px-10"><div className="mx-auto grid max-w-7xl gap-10 md:grid-cols-3"><div><img src="/lumora-logo.png" alt="Lumora Beauty Shop" className="h-14 w-auto brightness-0 invert" /><p className="mt-4 max-w-xs text-sm leading-6 text-[#cdbbb0]">Beautiful essentials for everyday rituals.<br />Made and delivered with care in Nairobi.</p></div><div><h3 className="text-xs font-semibold uppercase tracking-[0.2em] text-[#d7b7a6]">Come say hello</h3><p className="mt-4 flex items-start gap-3 text-sm text-[#cdbbb0]"><MapPin className="mt-0.5 size-4 shrink-0" /> Nairobi, Kenya<br /></p><a href="tel:+254702169678" className="mt-3 flex items-center gap-3 text-sm text-[#cdbbb0] hover:text-white"><MessageCircle className="size-4" /> 0702 169 678</a><a href="mailto:hello@lumorabeauty.co.ke" className="mt-3 flex items-center gap-3 text-sm text-[#cdbbb0] hover:text-white"><Mail className="size-4" /> hello@lumorabeauty.co.ke</a></div><div><h3 className="text-xs font-semibold uppercase tracking-[0.2em] text-[#d7b7a6]">Stay luminous</h3><p className="mt-4 text-sm leading-6 text-[#cdbbb0]">Follow our rituals and new arrivals.</p><a href="https://instagram.com" className="mt-4 inline-flex items-center gap-2 text-sm text-[#f8f5f0]"><Camera className="size-4" /> @lumorabeauty</a></div></div><div className="mx-auto mt-12 max-w-7xl border-t border-[#604941] pt-5 text-xs text-[#a8948a]">© 2026 Lumora Beauty Shop · Nairobi, Kenya</div></footer>
    {cartOpen && <div className="fixed inset-0 z-50 bg-[#3d2b27]/40" onClick={() => setCartOpen(false)}><aside onClick={(e) => e.stopPropagation()} className="absolute right-0 top-0 flex h-full w-full max-w-md flex-col bg-[#f8f5f0] p-6 shadow-2xl"><div className="flex items-center justify-between"><h2 className="font-serif text-3xl">Your basket</h2><button onClick={() => setCartOpen(false)} aria-label="Close basket"><X /></button></div>{cart.length === 0 ? <div className="flex flex-1 flex-col items-center justify-center gap-3 text-center text-[#806f68]"><ShoppingBag className="size-8" /><p>Your basket is waiting for something lovely.</p><a href="#shop" onClick={() => setCartOpen(false)} className="text-sm font-semibold text-[#b96752]">Explore products</a></div> : <><div className="flex flex-1 flex-col gap-5 overflow-auto py-8">{cart.map((item) => <div key={item.id} className="flex gap-4"><img src={item.image} alt="" className="size-20 rounded-xl object-cover" /><div className="flex-1"><div className="flex justify-between gap-3"><p className="font-serif text-lg">{item.name}</p><p className="text-sm font-semibold">{formatPrice(item.price * item.quantity)}</p></div><div className="mt-3 flex items-center gap-3"><button onClick={() => adjust(item.id, -1)} className="rounded-full border border-[#d9c9c0] p-1" aria-label="Decrease quantity"><Minus className="size-3" /></button><span className="text-sm">{item.quantity}</span><button onClick={() => adjust(item.id, 1)} className="rounded-full border border-[#d9c9c0] p-1" aria-label="Increase quantity"><Plus className="size-3" /></button></div></div></div>)}</div><div className="border-t border-[#e3d8d0] pt-5"><div className="flex justify-between font-serif text-xl"><span>Total</span><span>{formatPrice(total)}</span></div><button onClick={() => { setCartOpen(false); setCheckoutOpen(true) }} className="mt-5 w-full rounded-full bg-[#b96752] py-4 text-sm font-semibold text-white">Continue to checkout</button></div></>}</aside></div>}
    {checkoutOpen && <div className="fixed inset-0 z-50 flex items-center justify-center bg-[#3d2b27]/50 p-4"><div className="w-full max-w-lg rounded-3xl bg-[#f8f5f0] p-6 sm:p-8"><div className="flex items-start justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-[#b96752]">Almost yours</p><h2 className="mt-2 font-serif text-3xl">Complete your order</h2></div><button onClick={() => setCheckoutOpen(false)} aria-label="Close checkout"><X /></button></div><div className="mt-6 rounded-2xl bg-[#e9ddd3] p-5"><p className="text-xs font-semibold uppercase tracking-[0.15em] text-[#705c54]">Pay via Pochi la Biashara</p><p className="mt-2 font-serif text-2xl">0702 169 678</p><p className="mt-2 text-xs leading-5 text-[#806f68]">Send <strong>{formatPrice(total)}</strong> to Lumora Beauty Shop, then share your confirmation message on WhatsApp.</p></div><form onSubmit={(e) => { e.preventDefault(); setCheckoutOpen(false); setCart([]); alert('Thank you! Your order has been received. We will confirm it on WhatsApp shortly.') }} className="mt-6 flex flex-col gap-3"><input required placeholder="Full name" className="rounded-xl border border-[#d9c9c0] bg-transparent px-4 py-3 text-sm outline-none focus:border-[#b96752]" /><input required type="tel" placeholder="Phone number" className="rounded-xl border border-[#d9c9c0] bg-transparent px-4 py-3 text-sm outline-none focus:border-[#b96752]" /><input required placeholder="Delivery area in Nairobi" className="rounded-xl border border-[#d9c9c0] bg-transparent px-4 py-3 text-sm outline-none focus:border-[#b96752]" /><button className="mt-2 rounded-full bg-[#3d2b27] py-4 text-sm font-semibold text-white">Place order</button></form><a href="https://wa.me/254702169678" target="_blank" rel="noreferrer" className="mt-4 flex items-center justify-center gap-2 text-sm font-semibold text-[#52705e]"><MessageCircle className="size-4" /> Need help? WhatsApp us</a></div></div>}
  </div>
}

export default LumoraStore
