export const suppliedProducts = [
  { id: 101, brand: 'Anashe', name: 'Translucent Pressed Powder Medium', category: 'Makeup', price: 1530, description: 'Soft-focus pressed powder for a smooth finish.', image: '/products/lip-balm.png' },
  { id: 102, brand: 'Avène', name: 'Cleanance A.H.A Exfoliating Serum Gel 30ml', category: 'Skincare', price: 3278, description: 'Exfoliating serum gel for blemish-prone skin.', image: '/products/glow-mist.png' },
  { id: 103, brand: 'Avène', name: 'Cleanance Cleansing Gel 200ml', category: 'Skincare', price: 1906, description: 'Cleansing gel for oily and acne-prone skin.', image: '/products/hero-beauty.png' },
  { id: 104, brand: 'Avène', name: 'Cleanance Comedomed Concentrate 30ml', category: 'Skincare', price: 2287, description: 'Daily anti-blemish concentrate.', image: '/products/baobab-oil.png' },
  { id: 105, brand: 'Avène', name: 'Hydrance Light Hydrating Emulsion 40ml', category: 'Skincare', price: 2333, description: 'Lightweight hydration for comfortable skin.', image: '/products/body-butter.png' },
  { id: 106, brand: 'Avène', name: 'Thermal Spring Water Spray 150ml', category: 'Skincare', price: 2016, description: 'Refreshing thermal mist for sensitive skin.', image: '/products/glow-mist.png' },
  { id: 107, brand: 'CeraVe', name: 'Advanced Repair Ointment 88ml', category: 'Skincare', price: 2054, description: 'Protective ointment for very dry skin.', image: '/products/body-butter.png' },
  { id: 108, brand: 'CeraVe', name: 'Hydrating Hyaluronic Acid Serum 30ml', category: 'Skincare', price: 3341, description: 'Hydrating serum with hyaluronic acid.', image: '/products/baobab-oil.png' },
  { id: 109, brand: 'CeraVe', name: 'Hydrating Cleanser 236ml', category: 'Skincare', price: 1658, description: 'Gentle cleanser for normal to dry skin.', image: '/products/hero-beauty.png' },
  { id: 110, brand: 'CeraVe', name: 'Resurfacing Retinol Serum 30ml', category: 'Skincare', price: 3864, description: 'Refining retinol serum for smoother-looking skin.', image: '/products/glow-mist.png' },
  { id: 111, brand: 'Ducray', name: 'Keracnyl PP+ Anti-Blemish Cream 30ml', category: 'Skincare', price: 2823, description: 'Comforting anti-blemish care.', image: '/products/clay-mask.png' },
  { id: 112, brand: 'Ducray', name: 'Melascreen UV Protective Fluid SPF50+ 50ml', category: 'Skincare', price: 5318, description: 'High daily UV protection.', image: '/products/hero-beauty.png' },
  { id: 113, brand: 'Garnier', name: 'Cooling Watergel Sunscreen Vitamin C 30ml', category: 'Skincare', price: 1100, description: 'Lightweight vitamin C sunscreen.', image: '/products/glow-mist.png' },
  { id: 114, brand: 'Garnier', name: 'Pure Active Invisible Pimple Patch', category: 'Skincare', price: 1320, description: 'Discreet patches for visible blemishes.', image: '/products/clay-mask.png' },
  { id: 115, brand: 'Garnier', name: 'Vitamin C Serum Wash 100ml', category: 'Skincare', price: 950, description: 'Brightening daily face wash.', image: '/products/hero-beauty.png' },
  { id: 116, brand: 'Garnier', name: 'Acne Control Routine Kit', category: 'Skincare', price: 4199, description: 'Charcoal wash, AHA/BHA serum and air cream routine.', image: '/products/baobab-oil.png', badge: 'Routine kit' },
  { id: 117, brand: 'Garnier', name: 'Even & Bright Vitamin C Booster Serum 30ml', category: 'Skincare', price: 1482, description: 'Vitamin C booster for a radiant-looking tone.', image: '/products/glow-mist.png' },
  { id: 118, brand: 'Garnier', name: 'Pure Active Charcoal 3-in-1 150ml', category: 'Skincare', price: 1186, description: 'Cleanser, scrub and mask for combination skin.', image: '/products/clay-mask.png' },
  { id: 119, brand: 'Garnier', name: 'Even & Matte Micellar Water 100ml', category: 'Skincare', price: 520, description: 'Gentle makeup-removing micellar water.', image: '/products/glow-mist.png' },
  { id: 120, brand: 'Garnier', name: 'Hydra Bomb Chamomile Tissue Mask', category: 'Skincare', price: 375, description: 'Comforting sheet mask for hydrated skin.', image: '/products/clay-mask.png' },
  { id: 121, brand: "L'Oréal Paris", name: 'Laser Tri-Peptide Serum', category: 'Skincare', price: 2300, description: 'Peptide serum for a smoother-looking complexion.', image: '/products/baobab-oil.png' },
  { id: 122, brand: "L'Oréal Paris", name: 'Revitalift Filler Day Cream SPF50', category: 'Skincare', price: 3500, description: 'Daily moisturiser with high sun protection.', image: '/products/hero-beauty.png' },
  { id: 123, brand: "L'Oréal Paris", name: 'Curl Expression Shampoo 300ml', category: 'Hair Care', price: 2900, description: 'Professional shampoo for defined curls.', image: '/products/body-butter.png' },
  { id: 124, brand: "L'Oréal Paris", name: 'Curl Expression Curls Reviver 190ml', category: 'Hair Care', price: 3400, description: 'Refreshes and revives curls between washes.', image: '/products/glow-mist.png' },
  { id: 125, brand: "L'Oréal Paris", name: 'Curl Expression Mask 250ml', category: 'Hair Care', price: 2700, description: 'Deep conditioning curl mask.', image: '/products/body-butter.png' },
  { id: 126, brand: 'La Roche-Posay', name: 'Anthelios Lotion Eco SPF50+ 250ml', category: 'Skincare', price: 5482, description: 'High-protection body sunscreen.', image: '/products/hero-beauty.png' },
  { id: 127, brand: 'La Roche-Posay', name: 'Lipikar Syndet AP+ Refill 400ml', category: 'Body Care', price: 2611, description: 'Gentle cleansing cream for dry skin.', image: '/products/body-butter.png' },
  { id: 128, brand: 'La Roche-Posay', name: 'Vitamin C12 Serum 30ml', category: 'Skincare', price: 6521, description: 'Antioxidant brightening serum.', image: '/products/baobab-oil.png' },
  { id: 129, brand: 'La Roche-Posay', name: 'Effaclar Unspot Patches', category: 'Skincare', price: 2001, description: 'Targeted patches for blemishes.', image: '/products/clay-mask.png' },
  { id: 130, brand: 'Maybelline', name: 'Fit Me Powder', category: 'Makeup', price: 1300, description: 'Natural-looking pressed face powder.', image: '/products/lip-balm.png' },
  { id: 131, brand: 'Maybelline', name: 'Grippy Primer Serum', category: 'Makeup', price: 2800, description: 'Hydrating grip primer for lasting makeup.', image: '/products/glow-mist.png' },
  { id: 132, brand: 'Maybelline', name: 'Fit Me Foundation', category: 'Makeup', price: 1500, description: 'Buildable foundation with a natural finish.', image: '/products/hero-beauty.png' },
  { id: 133, brand: 'Maybelline', name: 'SuperStay Matte Ink', category: 'Makeup', price: 2100, description: 'Long-wear liquid matte lip colour.', image: '/products/lip-balm.png' },
  { id: 134, brand: 'Nivea', name: 'Visage Anti-Wrinkle Q10 Day Cream 50ml', category: 'Skincare', price: 2249, description: 'Q10 daily moisturiser.', image: '/products/body-butter.png' },
  { id: 135, brand: 'Nivea', name: 'Visage Anti-Wrinkle Q10 Night Cream 50ml', category: 'Skincare', price: 2024, description: 'Overnight nourishing cream.', image: '/products/baobab-oil.png' },
  { id: 136, brand: 'Nivea', name: 'Suntan Kids Lotion SPF50 200ml', category: 'Skincare', price: 2800, description: 'High protection kids sunscreen lotion.', image: '/products/hero-beauty.png' },
  { id: 137, brand: 'Simple', name: 'Hydrating Light Moisturiser 125ml', category: 'Skincare', price: 1458, description: 'Light moisturiser for sensitive skin.', image: '/products/body-butter.png' },
  { id: 138, brand: 'Simple', name: 'Purifying Cleansing Lotion 200ml', category: 'Skincare', price: 2159, description: 'Gentle purifying cleansing lotion.', image: '/products/glow-mist.png' },
  { id: 139, brand: 'Simple', name: 'Kind to Skin Refresh Facial Wash 150ml', category: 'Skincare', price: 1701, description: 'Refreshing, no-fuss facial wash.', image: '/products/hero-beauty.png' },
  { id: 140, brand: 'Uncover', name: 'Myravive Deep Hydrating & Repair Serum 30ml', category: 'Skincare', price: 3500, description: 'Deep hydration and barrier support.', image: '/products/baobab-oil.png' },
  { id: 141, brand: 'Uncover', name: 'Myravive Gentle Hydrating Cleanser 120ml', category: 'Skincare', price: 1850, description: 'Gentle hydrating daily cleanser.', image: '/products/glow-mist.png' },
  { id: 142, brand: 'Uncover', name: 'Aloe Invisible Sunscreen 80ml', category: 'Skincare', price: 2873, description: 'Invisible daily SPF protection.', image: '/products/hero-beauty.png' },
  { id: 143, brand: 'Uncover', name: 'Argan Hydrating Moisturizer 100ml', category: 'Skincare', price: 1823, description: 'Smoothing argan moisturiser.', image: '/products/body-butter.png' },
  { id: 144, brand: 'Uncover', name: 'Green Tea Revitalizing Cleanser 120ml', category: 'Skincare', price: 1650, description: 'Revitalising green tea cleanser.', image: '/products/glow-mist.png' },
  { id: 145, brand: 'Uncover', name: 'Rooibos Glow Toner 125ml', category: 'Skincare', price: 2030, description: 'Balancing toner for a fresh glow.', image: '/products/baobab-oil.png' },
  { id: 146, brand: 'Uncover', name: 'Complete 5 Step Skincare Routine', category: 'Skincare', price: 12800, description: 'Complete daily skincare routine set.', image: '/products/hero-beauty.png', badge: 'Routine kit' },
  { id: 147, brand: 'Nice & Lovely', name: 'Double Lemon 360ml Pack', category: 'Body Care', price: 504, description: 'Bright, refreshing body care pack.', image: '/products/body-butter.png' },
  { id: 148, brand: 'Skin by Zaron', name: 'Men Face & Body Lotion', category: 'Body Care', price: 3563, description: 'Moisturising face and body lotion.', image: '/products/body-butter.png' },
  { id: 149, brand: 'Skin by Zaron', name: 'Papaya Brightening Body Wash', category: 'Body Care', price: 3850, description: 'Papaya body wash for a fresh cleanse.', image: '/products/glow-mist.png' },
  { id: 150, brand: 'Skin by Zaron', name: 'Retinol Serum', category: 'Skincare', price: 3465, description: 'Refining serum for evening care.', image: '/products/baobab-oil.png' },
  { id: 151, brand: 'Skin by Zaron', name: 'Sun Protection Day Cream', category: 'Skincare', price: 3850, description: 'Protective daytime moisturiser.', image: '/products/hero-beauty.png' },
  { id: 152, brand: 'Global', name: 'Watermelon Sugar Scrub 600g', category: 'Body Care', price: 850, description: 'Exfoliating sugar scrub with watermelon scent.', image: '/products/body-butter.png' },
  { id: 153, brand: 'Global', name: 'Arabica Sugar Scrub 600g', category: 'Body Care', price: 850, description: 'Coffee-inspired body exfoliator.', image: '/products/body-butter.png' },
  { id: 154, brand: 'Global', name: 'Honey & Vanilla Scrub 600g', category: 'Body Care', price: 1000, description: 'Sweetly scented body scrub.', image: '/products/body-butter.png' },
  { id: 155, brand: 'Vaseline', name: 'Gluta SPF50 150ml', category: 'Body Care', price: 950, description: 'Brightening body lotion with sun protection.', image: '/products/body-butter.png' },
  { id: 156, brand: 'Vaseline', name: 'Body Wash 425ml', category: 'Body Care', price: 800, description: 'Creamy body wash for everyday cleansing.', image: '/products/glow-mist.png' },
  { id: 157, brand: 'Vatika', name: 'Hair Masque 500g', category: 'Hair Care', price: 300, description: 'Nourishing hair treatment masque.', image: '/products/body-butter.png' },
  { id: 158, brand: 'Vatika', name: 'Shampoo 400ml', category: 'Hair Care', price: 300, description: 'Everyday botanical hair cleanser.', image: '/products/hero-beauty.png' },
  { id: 159, brand: 'Tresemmé', name: 'Shampoo 828ml', category: 'Hair Care', price: 650, description: 'Salon-inspired cleansing shampoo.', image: '/products/hero-beauty.png' },
  { id: 160, brand: 'Veet', name: 'Green Dry Skin Cream 25ml', category: 'Body Care', price: 200, description: 'Easy hair removal cream for dry skin.', image: '/products/body-butter.png' },
] as const
